### PR TITLE
Remove unused method from Logger

### PR DESCRIPTION
**Pull request by arggh**

### CODE REVIEW

**Comment by FGM** [comment]
Hmm, IIRC it should be invoked by TK in some situations, but I don't remember which ones.

**Comment by arggh** [comment]
Interesting. It's quite late on this side of the screen, but in my unterstanding that's not even possible.

I even spent a while reading TraceKit's source code and couldn't find anything implying that it would, either.

I'd be really happy if somebody corrected me!

**Comment by fgm** [comment]
OK, so I spent some time looking for the explanation and found it. This is a facade (needed or not) to simplify stack trace obtention. Instead of doing :
```ecmascript 6
try {
  /* your application code here */
  throw new Error('oops');
} catch (e) {
  TraceKit.report(e);
}
```

Your Meteor application can use its own logger instance to log like this:
```ecmascript 6
try {
  /* your application code here */
  throw new Error('oops');
} catch (e) {
  logger.report(e);
}
```

Which is IMHO more convenient, especially as it allows switch TK instances. But this is only useful if you're not using arm/disarm() instead. This is how we used it originally.

So the question becomes: document it or remove it ?

**Comment by fgm** [comment]
Oops, sorry, I only meant to comment at this point, not close.

**Pull request closed without merging**
